import openapiTS, { astToString } from 'openapi-typescript';
import { OpenApiDocument, resolveSchemas } from './openapi-types';

// A schema key isn't guaranteed to be a valid TS identifier (an enterprise spec can use dotted or
// hyphenated names) — openapi-typescript itself tolerates that inside `components['schemas'][...]`
// index access, but `export type <name> = ...` cannot. Skipping a non-identifier name here (rather
// than emitting invalid syntax) is what makes this set the single source of truth for which types
// actually exist as named exports — generate-client.ts imports only names that pass this filter.
const VALID_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

export function emittableSchemaNames(doc: OpenApiDocument): string[] {
  return Object.keys(resolveSchemas(doc)).filter((name) => VALID_IDENTIFIER.test(name));
}

// openapi-typescript only understands OpenAPI 3.x — a Swagger 2.0 doc (doc.swagger set, no
// doc.openapi) has no `components.schemas` shape it recognizes, so calling it would either throw
// or silently emit nothing useful. Callers check this before generating schema.ts/types.ts at all,
// and generate-client.ts already falls back to `unknown` body/param types when no barrel exists.
export function supportsSchemaGeneration(doc: OpenApiDocument): boolean {
  return typeof doc.openapi === 'string';
}

// Generated by openapi-typescript itself — the full `paths`/`components` AST as source text. Not
// hand-parsed: this is exactly the library doing what it's designed for (allOf/oneOf/discriminators
// /nullable/security schemes — all the spec features the old hand-rolled generator didn't handle).
export async function generateSchemaFile(doc: OpenApiDocument): Promise<string> {
  const ast = await openapiTS(doc as Parameters<typeof openapiTS>[0]);
  const header = [
    '// Generated by openapi-typescript (invoked from src/api-onboarder) — do not hand-edit.',
    '// Re-run `npm run api-onboarder -- <spec-url>` to regenerate after the spec changes.',
    '',
  ].join('\n');
  return `${header}${astToString(ast)}`;
}

// A thin barrel of named aliases over schema.ts's `components['schemas'][...]` index type — this
// is what keeps generate-client.ts's `import { Pet } from './types'` pattern working unchanged
// regardless of which library renders the underlying schema shapes.
export function generateTypesBarrel(doc: OpenApiDocument): string {
  const header = [
    '// Generated by src/api-onboarder — do not hand-edit.',
    "// Named aliases over schema.ts's generated `components` interface, so callers can import a",
    "// schema by name (`import { Pet } from './types'`) instead of indexing into `components`.",
    '',
    "import { components } from './schema';",
    '',
  ].join('\n');
  const aliases = emittableSchemaNames(doc)
    .sort()
    .map((name) => `export type ${name} = components['schemas']['${name}'];`);
  return `${header}${aliases.join('\n')}\n`;
}
