import { OpenApiDocument, OpenApiMethod, OpenApiOperation, OpenApiParameter, refName } from './openapi-types';

// Matches the shape every hand-written client in src/api/clients/*.client.ts already uses:
// constructor(request: APIRequestContext), one method per endpoint, method body is a single
// this.request.<verb>(url, opts) call returning the raw APIResponse untouched — callers decide
// what status/body to expect, the client never asserts or unwraps.

function paramsByLocation(params: OpenApiParameter[] | undefined, loc: OpenApiParameter['in']): OpenApiParameter[] {
  return (params ?? []).filter((p) => p.in === loc);
}

function tsParamType(param: OpenApiParameter): string {
  if (param.schema?.$ref) return refName(param.schema.$ref);
  if (param.type === 'integer' || param.type === 'number') return 'number';
  if (param.type === 'boolean') return 'boolean';
  return 'string';
}

// camelCase(operationId) would collide with operationId's own casing conventions across specs
// (some are already camelCase, some kebab/snake) — operationId is used as the method name
// verbatim since Swagger/OpenAPI already requires it to be a valid identifier-ish token, and
// diverging from it would make the generated method harder to trace back to the spec.
function methodName(operationId: string | undefined, method: OpenApiMethod, urlPath: string): string {
  if (operationId) return operationId;
  // Fallback for a spec that omits operationId on some operations: derive a name from the path
  // and verb so every operation still gets a callable method instead of being silently dropped.
  const slug = urlPath
    .replace(/[{}]/g, '')
    .split('/')
    .filter(Boolean)
    .map((seg, i) => (i === 0 ? seg : seg[0].toUpperCase() + seg.slice(1)))
    .join('');
  return `${method}${slug[0].toUpperCase()}${slug.slice(1)}`;
}

function renderMethod(urlPath: string, method: OpenApiMethod, op: OpenApiOperation): string {
  const pathParams = paramsByLocation(op.parameters, 'path');
  const queryParams = paramsByLocation(op.parameters, 'query');
  const bodyParam = paramsByLocation(op.parameters, 'body')[0];

  const args = [
    ...pathParams.map((p) => `${p.name}: ${tsParamType(p)}`),
    ...queryParams.map((p) => `${p.name}${p.required ? '' : '?'}: ${tsParamType(p)}`),
    ...(bodyParam ? [`body: ${bodyParam.schema?.$ref ? refName(bodyParam.schema.$ref) : 'unknown'}`] : []),
  ].join(', ');

  // Template-literal path with {param} substituted directly — Swagger/OpenAPI path templates
  // already use the same {param} syntax as a JS template literal once braces are kept as-is.
  const urlExpr = '`${this.baseUrl}' + urlPath.replace(/{(\w+)}/g, '${$1}') + '`';

  const optsLines: string[] = [];
  if (queryParams.length > 0) {
    const paramsObj = queryParams.map((p) => p.name).join(', ');
    optsLines.push(`params: { ${paramsObj} }`);
  }
  if (bodyParam) optsLines.push('data: body');
  const opts = optsLines.length > 0 ? `, {\n      ${optsLines.join(',\n      ')},\n    }` : '';

  const name = methodName(op.operationId, method, urlPath);
  return [`  async ${name}(${args}) {`, `    return this.request.${method}(${urlExpr}${opts});`, `  }`].join('\n');
}

export function generateClientFile(doc: OpenApiDocument, className: string, baseUrl: string): string {
  const methods: string[] = [];
  for (const [urlPath, pathItem] of Object.entries(doc.paths)) {
    for (const method of ['get', 'post', 'put', 'patch', 'delete'] as OpenApiMethod[]) {
      const op = pathItem[method];
      if (!op) continue;
      methods.push(renderMethod(urlPath, method, op));
    }
  }

  const typeNames = new Set<string>();
  for (const pathItem of Object.values(doc.paths)) {
    for (const method of ['get', 'post', 'put', 'patch', 'delete'] as OpenApiMethod[]) {
      const op = pathItem[method];
      if (!op) continue;
      for (const p of op.parameters ?? []) {
        if (p.schema?.$ref) typeNames.add(refName(p.schema.$ref));
      }
    }
  }
  const typeImport = typeNames.size > 0 ? `import { ${[...typeNames].sort().join(', ')} } from './types';\n` : '';

  return [
    '// Generated by src/api-onboarder from the OpenAPI/Swagger document — do not hand-edit.',
    '// Re-run `npm run api-onboarder -- <spec-url>` to regenerate after the spec changes.',
    '',
    "import { APIRequestContext } from '@playwright/test';",
    typeImport,
    `export class ${className} {`,
    `  private readonly baseUrl = '${baseUrl}';`,
    '',
    '  constructor(private readonly request: APIRequestContext) {}',
    '',
    methods.join('\n\n'),
    '}',
    '',
  ].join('\n');
}
