import { OpenApiDocument, OpenApiSchema, refName, resolveSchemas } from './openapi-types';

// Swagger/OpenAPI primitive types map onto TS primitives directly except integer, which has no TS
// equivalent — both fold to `number`. Anything unrecognized (a spec authoring slip, a type this
// module doesn't handle yet) becomes `unknown` rather than guessing, so a generated file always
// compiles instead of silently emitting an invalid type name.
function primitiveType(schema: OpenApiSchema): string {
  switch (schema.type) {
    case 'integer':
    case 'number':
      return 'number';
    case 'string':
      return schema.enum ? schema.enum.map((v) => `'${v}'`).join(' | ') : 'string';
    case 'boolean':
      return 'boolean';
    default:
      return 'unknown';
  }
}

function propertyType(schema: OpenApiSchema): string {
  if (schema.$ref) return refName(schema.$ref);
  if (schema.type === 'array') return `${schema.items ? propertyType(schema.items) : 'unknown'}[]`;
  if (schema.type === 'object' || schema.properties) return renderInlineObject(schema);
  return primitiveType(schema);
}

function renderInlineObject(schema: OpenApiSchema): string {
  if (!schema.properties) return 'Record<string, unknown>';
  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties).map(([name, propSchema]) => {
    const optional = required.has(name) ? '' : '?';
    return `${name}${optional}: ${propertyType(propSchema)};`;
  });
  return `{ ${fields.join(' ')} }`;
}

function renderInterface(name: string, schema: OpenApiSchema): string {
  if (schema.type !== 'object' && !schema.properties) {
    // A top-level schema that isn't an object (e.g. a bare string enum) becomes a type alias —
    // an `interface X = string` isn't legal TS, so this can't reuse renderInterface's shape.
    return `export type ${name} = ${propertyType(schema)};`;
  }
  const required = new Set(schema.required ?? []);
  const properties = schema.properties ?? {};
  const fields = Object.entries(properties).map(([propName, propSchema]) => {
    const optional = required.has(propName) ? '' : '?';
    return `  ${propName}${optional}: ${propertyType(propSchema)};`;
  });
  return `export interface ${name} {\n${fields.join('\n')}\n}`;
}

// One flat file, one interface (or type alias) per schema — deterministic order (declaration
// order from the spec) so a re-run against the same spec produces a byte-identical diff, which
// matters for reviewing what changed when a spec is re-onboarded later.
export function generateTypesFile(doc: OpenApiDocument): string {
  const schemas = resolveSchemas(doc);
  const header = [
    '// Generated by src/api-onboarder from the OpenAPI/Swagger document — do not hand-edit.',
    '// Re-run `npm run api-onboarder -- <spec-url>` to regenerate after the spec changes.',
    '',
  ].join('\n');
  const body = Object.entries(schemas)
    .map(([name, schema]) => renderInterface(name, schema))
    .join('\n\n');
  return `${header}${body}\n`;
}
