import * as fs from 'fs';
import { execFileSync } from 'child_process';
import { findRecoveries } from './find-recoveries';

const SELF_HEAL_CACHE = '.self-heal/healed_locators.json';
const BRANCH_PREFIX = 'agent-fixer/';
const SKIP_MARKER = 'agent-fixer: skip';

function currentBranch(): string {
  return execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD']).toString().trim();
}

function main(): void {
  if (currentBranch().startsWith(BRANCH_PREFIX)) {
    process.stderr.write('[agent-fixer] running on an agent-fixer branch — skipping to avoid a loop\n');
    return;
  }

  const recoveries = findRecoveries();
  const brokenSelectors = new Set<string>();
  for (const step of recoveries) {
    for (const err of step.recoveredErrors ?? []) {
      if (err.selector) brokenSelectors.add(err.selector);
    }
  }

  if (brokenSelectors.size === 0) {
    process.stderr.write('[agent-fixer] no passed_with_recovery steps found — nothing to fix\n');
    return;
  }

  if (!fs.existsSync(SELF_HEAL_CACHE)) {
    process.stderr.write('[agent-fixer] recoveries found but .self-heal/healed_locators.json is missing — cannot propose a fix\n');
    return;
  }
  const healedCache = fs.readFileSync(SELF_HEAL_CACHE, 'utf-8');

  const branch = `${BRANCH_PREFIX}${Date.now()}`;
  execFileSync('git', ['checkout', '-b', branch], { stdio: 'inherit' });

  const prompt = [
    'You are fixing broken UI locators in a Playwright + TypeScript test suite.',
    '',
    'Each of these selectors is broken in source — it no longer matches anything on the page —',
    'but healwright (a runtime self-healing wrapper) silently recovered it during the last test',
    'run, so the test itself stayed green:',
    '',
    ...[...brokenSelectors].map((s) => `- ${s}`),
    '',
    'Here is healwright\'s cache of the working replacement it found for each broken locator,',
    `from ${SELF_HEAL_CACHE}:`,
    '',
    '```json',
    healedCache,
    '```',
    '',
    'Each cache entry\'s "context" field is exactly the contextName string passed as the second',
    'argument to `heal.click(locator, contextName)` in src/ui/pages/practice-form.page.ts — use',
    'that to match each broken selector (found as the first `heal.click` argument on the same',
    'line) to its cache entry, then read the "strategy" field (or the flat type/role/name/',
    'selector/text/value fields alongside "context") to build the replacement Playwright locator.',
    '',
    'IMPORTANT — before changing anything, check the two lines above and below each match for a',
    `comment containing "${SKIP_MARKER}". If present, leave that exact heal.click call untouched`,
    'and do not report it as fixed — it is a deliberately-broken fixture for a different demo, not',
    'a real bug.',
    '',
    'For every other broken locator: replace only the first argument of its heal.click(...) call',
    '(the broken Locator) with a Locator built from the matched working strategy — e.g.',
    'page.getByRole(role, { name }) for a "role" strategy, page.locator(selector) for a "css"',
    'strategy. Keep the heal.click(...) wrapper and the contextName argument unchanged. Do not',
    'touch any locator you cannot confidently match to a cache entry. Do not change anything',
    'outside src/ui/pages/practice-form.page.ts.',
    '',
    'After editing, run `npx tsc --noEmit` to confirm the change compiles, and fix any type error',
    'your edit introduced before finishing.',
  ].join('\n');

  execFileSync(
    'claude',
    [
      '-p',
      prompt,
      '--permission-mode',
      'acceptEdits',
      '--allowedTools',
      'Read,Edit,Grep,Glob,Bash(npx tsc --noEmit)',
    ],
    { stdio: 'inherit' },
  );

  const diff = execFileSync('git', ['status', '--porcelain']).toString();
  if (!diff.trim()) {
    process.stderr.write('[agent-fixer] claude made no changes — skipping commit/PR\n');
    execFileSync('git', ['checkout', 'master'], { stdio: 'inherit' });
    execFileSync('git', ['branch', '-D', branch], { stdio: 'inherit' });
    return;
  }

  execFileSync('git', ['add', 'src/ui/pages/practice-form.page.ts'], { stdio: 'inherit' });
  execFileSync(
    'git',
    [
      'commit',
      '-m',
      'agent-fixer: replace healwright-recovered locators\n\nAuto-generated from .observability/ passed_with_recovery records.',
    ],
    { stdio: 'inherit' },
  );
  execFileSync('git', ['push', 'origin', branch], { stdio: 'inherit' });
  execFileSync(
    'gh',
    [
      'pr',
      'create',
      '--title',
      'agent-fixer: replace healwright-recovered locators',
      '--body',
      [
        'Auto-generated by agent-fixer from `.observability/` `passed_with_recovery` records.',
        '',
        'Broken selectors found:',
        ...[...brokenSelectors].map((s) => `- \`${s}\``),
        '',
        `See \`${SELF_HEAL_CACHE}\` in this branch for the exact strategy/confidence healwright used to recover each one at runtime — review the confidence before merging, a low-confidence match may be overfit to one page state.`,
      ].join('\n'),
    ],
    { stdio: 'inherit' },
  );
}

main();
