import * as fs from 'fs';
import { execFileSync } from 'child_process';
import { findRecoveries } from './find-recoveries';
import { proposeFixesWithGemini } from './fix-proposer';

const SELF_HEAL_CACHE = '.self-heal/healed_locators.json';
const TARGET_FILE = 'src/ui/pages/practice-form.page.ts';
const BRANCH_PREFIX = 'agent-fixer/';
const SKIP_MARKER = 'agent-fixer: skip';

function currentBranch(): string {
  return execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD']).toString().trim();
}

// True if a line within `contextLines` above the match carries the skip marker.
function isSkipped(fileLines: string[], matchLineIndex: number, contextLines = 3): boolean {
  const start = Math.max(0, matchLineIndex - contextLines);
  return fileLines.slice(start, matchLineIndex + 1).some((l) => l.includes(SKIP_MARKER));
}

function applyReplacement(selector: string, replacementCode: string): boolean {
  const source = fs.readFileSync(TARGET_FILE, 'utf-8');
  const lines = source.split('\n');
  const needle = `this.page.locator('${selector}')`;
  const lineIndex = lines.findIndex((l) => l.includes(needle));
  if (lineIndex === -1) {
    process.stderr.write(`[agent-fixer] selector ${selector} not found in ${TARGET_FILE} — skipping\n`);
    return false;
  }
  if (isSkipped(lines, lineIndex)) {
    process.stderr.write(`[agent-fixer] ${selector} is marked "${SKIP_MARKER}" — leaving it untouched\n`);
    return false;
  }
  const replacementWithThis = replacementCode.startsWith('page.') ? `this.${replacementCode}` : replacementCode;
  lines[lineIndex] = lines[lineIndex].replace(needle, replacementWithThis);
  fs.writeFileSync(TARGET_FILE, lines.join('\n'));
  return true;
}

async function main(): Promise<void> {
  if (currentBranch().startsWith(BRANCH_PREFIX)) {
    process.stderr.write('[agent-fixer] running on an agent-fixer branch — skipping to avoid a loop\n');
    return;
  }

  const recoveries = findRecoveries();
  const brokenSelectors = new Set<string>();
  for (const step of recoveries) {
    for (const err of step.recoveredErrors ?? []) {
      if (err.selector) brokenSelectors.add(err.selector);
    }
  }

  if (brokenSelectors.size === 0) {
    process.stderr.write('[agent-fixer] no passed_with_recovery steps found — nothing to fix\n');
    return;
  }

  if (!fs.existsSync(SELF_HEAL_CACHE)) {
    process.stderr.write(`[agent-fixer] recoveries found but ${SELF_HEAL_CACHE} is missing — cannot propose a fix\n`);
    return;
  }
  const healedCacheJson = fs.readFileSync(SELF_HEAL_CACHE, 'utf-8');

  // Drop selectors marked "agent-fixer: skip" in source before even asking the model —
  // no point spending a call proposing a fix we won't apply.
  const sourceLines = fs.readFileSync(TARGET_FILE, 'utf-8').split('\n');
  const candidateSelectors = [...brokenSelectors].filter((selector) => {
    const lineIndex = sourceLines.findIndex((l) => l.includes(`this.page.locator('${selector}')`));
    return lineIndex !== -1 && !isSkipped(sourceLines, lineIndex);
  });

  if (candidateSelectors.length === 0) {
    process.stderr.write('[agent-fixer] all recovered selectors are marked "agent-fixer: skip" — nothing to fix\n');
    return;
  }

  const proposals = await proposeFixesWithGemini(candidateSelectors, healedCacheJson);

  const branch = `${BRANCH_PREFIX}${Date.now()}`;
  execFileSync('git', ['checkout', '-b', branch], { stdio: 'inherit' });

  const applied: { selector: string; replacementCode: string }[] = [];
  for (const proposal of proposals) {
    if (!proposal.found || !proposal.replacementCode) {
      process.stderr.write(`[agent-fixer] no confident fix for ${proposal.selector}: ${proposal.reason ?? 'unknown'}\n`);
      continue;
    }
    if (applyReplacement(proposal.selector, proposal.replacementCode)) {
      applied.push({ selector: proposal.selector, replacementCode: proposal.replacementCode });
    }
  }

  if (applied.length === 0) {
    process.stderr.write('[agent-fixer] no fixes applied — nothing to commit\n');
    execFileSync('git', ['checkout', 'master'], { stdio: 'inherit' });
    execFileSync('git', ['branch', '-D', branch], { stdio: 'inherit' });
    return;
  }

  execFileSync('npx', ['tsc', '--noEmit'], { stdio: 'inherit' });

  execFileSync('git', ['add', TARGET_FILE], { stdio: 'inherit' });
  execFileSync(
    'git',
    [
      'commit',
      '-m',
      'agent-fixer: replace healwright-recovered locators\n\nAuto-generated from .observability/ passed_with_recovery records.',
    ],
    { stdio: 'inherit' },
  );
  execFileSync('git', ['push', 'origin', branch], { stdio: 'inherit' });
  execFileSync(
    'gh',
    [
      'pr',
      'create',
      '--title',
      'agent-fixer: replace healwright-recovered locators',
      '--body',
      [
        'Auto-generated by agent-fixer from `.observability/` `passed_with_recovery` records.',
        '',
        'Fixes applied:',
        ...applied.map((f) => `- \`${f.selector}\` -> \`${f.replacementCode}\``),
        '',
        `See \`${SELF_HEAL_CACHE}\` in this branch for the exact strategy/confidence healwright used to recover each one at runtime — review the confidence before merging, a low-confidence match may be overfit to one page state.`,
      ].join('\n'),
    ],
    { stdio: 'inherit' },
  );
}

main().catch((err) => {
  process.stderr.write(`[agent-fixer] failed: ${err.message}\n`);
  process.exitCode = 1;
});
