import * as fs from 'fs';
import { execFileSync } from 'child_process';
import { proposeTest } from './propose-test';

const REFERENCE_FILE = 'tests/api/negative.spec.ts';
const OUTPUT_FILE = `tests/api/negative-generated-${Date.now()}.spec.ts`;
const BRANCH_PREFIX = 'test-evolution/';

function currentBranch(): string {
  return execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD']).toString().trim();
}

function runGeneratedSpec(file: string): boolean {
  try {
    execFileSync('npx', ['playwright', 'test', file, '--project=api', '--retries=0'], { stdio: 'inherit' });
    return true;
  } catch {
    return false;
  }
}

function abandon(branch: string, reason: string, removeOutputFile: boolean): void {
  process.stderr.write(`[test-evolution] ${reason}\n`);
  if (removeOutputFile && fs.existsSync(OUTPUT_FILE)) fs.unlinkSync(OUTPUT_FILE);
  execFileSync('git', ['checkout', 'master'], { stdio: 'inherit' });
  execFileSync('git', ['branch', '-D', branch], { stdio: 'inherit' });
}

async function main(): Promise<void> {
  if (currentBranch().startsWith(BRANCH_PREFIX)) {
    process.stderr.write('[test-evolution] running on a test-evolution branch — skipping to avoid a loop\n');
    return;
  }

  const branch = `${BRANCH_PREFIX}${Date.now()}`;
  execFileSync('git', ['checkout', '-b', branch], { stdio: 'inherit' });

  // CLI failures (quota, rate limit, network) must not leave an orphaned branch behind — same
  // isolation agent-fixer applies around its own Gemini CLI call. proposeTest() already falls
  // back from gemini to claude internally on any failure, so reaching this catch means both CLIs
  // failed.
  try {
    proposeTest(REFERENCE_FILE, OUTPUT_FILE);
  } catch (err) {
    abandon(branch, `AI CLI failed (gemini, then claude fallback): ${(err as Error).message}`, false);
    return;
  }

  if (!fs.existsSync(OUTPUT_FILE)) {
    abandon(branch, 'no file was generated — nothing to propose', false);
    return;
  }

  process.stderr.write(`[test-evolution] generated ${OUTPUT_FILE} — running it to verify it actually passes\n`);
  const passed = runGeneratedSpec(OUTPUT_FILE);

  if (!passed) {
    abandon(branch, 'generated test did not pass — discarding, not proposing a PR for a test that fails', true);
    return;
  }

  process.stderr.write(`[test-evolution] ${OUTPUT_FILE} passed — committing and opening a PR\n`);

  execFileSync('npx', ['tsc', '--noEmit'], { stdio: 'inherit' });

  execFileSync('git', ['add', OUTPUT_FILE], { stdio: 'inherit' });
  execFileSync(
    'git',
    [
      'commit',
      '-m',
      `test-evolution: propose a new edge-case test\n\nGenerated from ${REFERENCE_FILE}, verified to pass before being committed.`,
    ],
    { stdio: 'inherit' },
  );
  execFileSync('git', ['push', 'origin', branch], { stdio: 'inherit' });
  execFileSync(
    'gh',
    [
      'pr',
      'create',
      '--draft',
      '--title',
      'test-evolution: propose a new edge-case test',
      '--body',
      [
        `Auto-generated by test-evolution from \`${REFERENCE_FILE}\`.`,
        '',
        `New file: \`${OUTPUT_FILE}\` — already run once (\`--project=api --retries=0\`) and confirmed passing`,
        'before this PR was opened. Review the assertion itself for correctness (a passing test can',
        'still assert the wrong thing — see the file header comment in `src/test-evolution/propose-test.ts`',
        'for why this only proposes tests it can demonstrate hold, not tests it can prove are *right*).',
      ].join('\n'),
    ],
    { stdio: 'inherit' },
  );
}

main().catch((err) => {
  process.stderr.write(`[test-evolution] failed: ${err.message}\n`);
  process.exitCode = 1;
});
