import { test, expect } from '@playwright/test';
import { renderPageKnowledgeMarkdown, ReconResult } from '../../src/goal-evolution/recon';

function baseResult(overrides: Partial<ReconResult> = {}): ReconResult {
  return {
    url: 'https://demoqa.com/alerts',
    elements: [{ tag: 'button', id: 'alertButton', role: null, text: 'Click me' }],
    idsUnstableAcrossLoads: [],
    dialogs: [],
    ...overrides,
  };
}

test.describe('renderPageKnowledgeMarkdown', () => {
  test('marks the file as auto-generated with observed-facts-only wording', () => {
    const md = renderPageKnowledgeMarkdown('alerts', baseResult());
    expect(md).toContain('Auto-generated by `npm run goal-evolution:new`');
    expect(md).toContain('observed facts only');
  });

  test('lists every enumerated element in the table', () => {
    const md = renderPageKnowledgeMarkdown(
      'alerts',
      baseResult({
        elements: [
          { tag: 'button', id: 'alertButton', role: null, text: 'Click me' },
          { tag: 'a', id: null, role: null, text: 'Text Box' },
        ],
      }),
    );
    expect(md).toContain('| button | alertButton | _(none)_ | Click me |');
    expect(md).toContain('| a | _(none)_ | _(none)_ | Text Box |');
  });

  test('omits the unstable-ids section entirely when none were found', () => {
    const md = renderPageKnowledgeMarkdown('alerts', baseResult({ idsUnstableAcrossLoads: [] }));
    expect(md).not.toContain('IDs observed to change across page loads');
  });

  test('lists unstable ids with a locator warning when found', () => {
    const md = renderPageKnowledgeMarkdown('buttons', baseResult({ idsUnstableAcrossLoads: ['Ii9O4'] }));
    expect(md).toContain('IDs observed to change across page loads');
    expect(md).toContain('`Ii9O4`');
    expect(md).toContain('use role/text instead');
  });

  test('a dialog with observed result text renders "sets ... to:" not "not found"', () => {
    const md = renderPageKnowledgeMarkdown(
      'alerts',
      baseResult({
        dialogs: [
          {
            elementId: 'confirmButton',
            dialogType: 'confirm',
            message: 'Do you confirm action?',
            afterAccept: { elementId: 'confirmResult', text: 'You selected Ok' },
            afterDismiss: { elementId: 'confirmResult', text: 'You selected Cancel' },
          },
        ],
      }),
    );
    expect(md).toContain('Accepting sets `#confirmResult` to: "You selected Ok"');
    expect(md).toContain('Dismissing sets `#confirmResult` to: "You selected Cancel"');
    expect(md).not.toContain('NOT found in the DOM');
  });

  test('a dialog whose result element never appears renders "NOT found", not empty-string text', () => {
    const md = renderPageKnowledgeMarkdown(
      'alerts',
      baseResult({
        dialogs: [
          {
            elementId: 'promtButton',
            dialogType: 'prompt',
            message: 'Please enter your name',
            afterAccept: { elementId: 'promptResult', text: 'You entered recon probe text' },
            afterDismiss: { elementId: 'promtButtonResult', text: null },
          },
        ],
      }),
    );
    expect(md).toContain('Dismissing: `#promtButtonResult` was NOT found in the DOM afterward (element absent, not empty text)');
  });

  test('omits the dialogs section entirely when none were observed', () => {
    const md = renderPageKnowledgeMarkdown('links', baseResult({ dialogs: [] }));
    expect(md).not.toContain('Native dialogs observed');
  });
});
